package: igor_rexstan
version: '2.0.0'
letzte Änderung: 2025-11-12 14:00
author: 'Christoph Böcker'
supportpage: 'https://github.com/christophboecker/igor_rexstan'

pages:
    rexstan/settings:
        title: translate:igor_rexstan_settings
        icon: fa fa-warning text-info
    rexstan/analysis:
        title: translate:igor_rexstan_analysis
        icon: fa fa-warning text-info
        linkAttr: 
            onclick: 'Igor.rex_loader.show()'

requires:
    php:
        version: '^8.1'
    packages:
        rexstan: '>=2.0.0'
    redaxo: '^5.13.0'
